# Generated by Django 5.2.7 on 2025-10-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='machine_choice',
            field=models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_choice',
            field=models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], max_length=1),
        ),
    ]
